import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { DOCS, OUT, REPO, TARGET, type Row } from "./audit";

// Collect every screen's rows into a report. Always: .persona-qa/audit/button-audit.md.
// PERSONA_AUDIT_DOCS=1: also docs/qa/button-audit/rows-<target>.json and the generated section
// of docs/qa/button-audit.md (between the audit:generated markers; hand-written text is kept).
const START = "<!-- audit:generated:start -->";
const END = "<!-- audit:generated:end -->";
const ORDER = ["FAIL", "BLOCKED", "FIXME", "SKIP", "PASS"];

function load(dir: string): Row[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter((f) => f.endsWith(".json")).flatMap((f) => JSON.parse(readFileSync(join(dir, f), "utf8")) as Row[]);
}

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

function section(target: string, rows: Row[]): string {
  if (!rows.length) return `### ${target.toUpperCase()}\n\nNot run.\n`;
  const count = (r: string) => rows.filter((x) => x.result === r).length;
  const sorted = [...rows].sort((a, b) => a.screen.localeCompare(b.screen) || a.control.localeCompare(b.control) || a.viewport.localeCompare(b.viewport));
  const lines = [
    `### ${target.toUpperCase()}`,
    "",
    `**${rows.length} checks: ${count("PASS")} PASS, ${count("FAIL")} FAIL, ${count("FIXME")} FIXME (owned elsewhere), ${count("SKIP")} SKIP, ${count("BLOCKED")} BLOCKED (bot checkpoint).** Screens: ${new Set(rows.map((r) => r.screen)).size}.`,
    "",
  ];
  const bad = sorted.filter((r) => r.result !== "PASS" && r.result !== "SKIP");
  if (bad.length) {
    lines.push("Failures:", "");
    for (const r of bad) lines.push(`- **${r.result}** ${r.screen} / ${r.viewport} / \`${esc(r.control)}\` — ${esc(r.note)}`);
    lines.push("");
  }
  lines.push("| screen | control | viewport | expected | result |", "|---|---|---|---|---|");
  for (const r of sorted) lines.push(`| ${r.screen} | \`${esc(r.control)}\` | ${r.viewport} | ${esc(r.expected)} | ${r.result}${r.note ? ` — ${esc(r.note)}` : ""} |`);
  return lines.join("\n") + "\n";
}

export default function globalTeardown() {
  const rows = load(join(OUT, "rows")).sort((a, b) => ORDER.indexOf(a.result) - ORDER.indexOf(b.result));
  mkdirSync(OUT, { recursive: true });
  writeFileSync(join(OUT, "button-audit.md"), `# Button audit (${TARGET}, ${new Date().toISOString()})\n\n${section(TARGET, rows)}`);
  console.log(`[audit] ${rows.length} rows -> .persona-qa/audit/button-audit.md`);
  if (!DOCS) return;
  const dir = join(REPO, "docs/qa/button-audit");
  mkdirSync(dir, { recursive: true });
  if (rows.length) writeFileSync(join(dir, `rows-${TARGET}.json`), JSON.stringify(rows, null, 1) + "\n");
  const byTarget = (t: string) => (existsSync(join(dir, `rows-${t}.json`)) ? (JSON.parse(readFileSync(join(dir, `rows-${t}.json`), "utf8")) as Row[]) : []);
  const gen = `${START}\n\n_Generated by \`e2e/audit/teardown.ts\` (last ${TARGET} run ${new Date().toISOString()})._\n\n${section("local", byTarget("local"))}\n${section("live", byTarget("live"))}\n${END}`;
  const md = join(REPO, "docs/qa/button-audit.md");
  const cur = existsSync(md) ? readFileSync(md, "utf8") : `# Button audit (AUDIT-001)\n\n${START}\n${END}\n`;
  const out = cur.includes(START) ? cur.slice(0, cur.indexOf(START)) + gen + cur.slice(cur.indexOf(END) + END.length) : `${cur}\n${gen}\n`;
  writeFileSync(md, out);
  console.log(`[audit] docs/qa/button-audit.md updated (${TARGET})`);
}
