#!/usr/bin/env node
// docs/design/tokens.json -> app/tokens.css (CSS custom properties). The generated file is
// committed so the app builds without the docs tree; `--check` fails if it is stale.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, "../../../docs/design/tokens.json");
const OUT = join(HERE, "../app/tokens.css");

if (!existsSync(SRC)) {
  console.log("[tokens] docs/design/tokens.json not found; keeping committed app/tokens.css");
  process.exit(0);
}
const t = JSON.parse(readFileSync(SRC, "utf8"));
const px = (n) => (typeof n === "number" ? `${n}px` : n);
const lines = [];
for (const [k, v] of Object.entries(t.color)) lines.push(`--${k}: ${v};`);
lines.push(`--font: ${t.font.family};`);
for (const [k, v] of Object.entries(t.type)) {
  lines.push(`--t-${k}: ${v.weight} ${v.size}px/${v.lineHeight} var(--font);`);
  if (v.tracking) lines.push(`--tr-${k}: ${v.tracking};`);
  if (v.mobileSize) lines.push(`--t-${k}-mobile-size: ${v.mobileSize}px;`);
}
for (const [k, v] of Object.entries(t.space)) lines.push(`--${k}: ${px(v)};`);
for (const [k, v] of Object.entries(t.radius)) lines.push(`--r-${k}: ${px(v)};`);
for (const [k, v] of Object.entries(t.shadow)) lines.push(`--shadow-${k}: ${v};`);
for (const k of ["fast", "base", "slow", "ease-out", "ease-in-out"]) lines.push(`--m-${k}: ${t.motion[k]};`);
lines.push(`--chat-max: ${px(t.layout["chat-column-max"])};`);
lines.push(`--rail-w: ${px(t.layout["call-rail-width"])};`);
lines.push(`--gmail-card-max: ${px(t.layout["gmail-card-max"])};`);
lines.push(`--home-max: ${px(t.layout["home-column-max"])};`);
lines.push(`--hit-min: ${px(t.layout["hit-target-min"])};`);

const css = `/* GENERATED by apps/web/scripts/tokens-css.mjs from docs/design/tokens.json — do not edit. */\n:root {\n${lines.map((l) => "  " + l).join("\n")}\n}\n`;
if (process.argv.includes("--check")) {
  const cur = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (cur !== css) {
    console.error("[tokens] app/tokens.css is stale; run npm -w apps/web run tokens");
    process.exit(1);
  }
  process.exit(0);
}
writeFileSync(OUT, css);
console.log(`[tokens] wrote ${OUT}`);
