// GENERATED by `npm run flow:types` from packages/flow/flow.yaml — do not edit.
// Types and labels only: transitions are decided by the Python brain, never the browser.

export const FLOW_ID = "persona-onboarding";
export const FLOW_VERSION = 1;

export const SLOT_NAMES = ["agent_name", "user_name", "need", "gmail"] as const;
export type SlotName = (typeof SLOT_NAMES)[number];

export const NODE_IDS = ["greet", "agent_name", "call_offer", "user_name", "need", "gmail", "value_demo", "graduated"] as const;
export type NodeId = (typeof NODE_IDS)[number];

export const INTENTS = ["insist_graduate", "refuse_slot", "change_answer", "unsure_need", "off_topic", "privacy_question", "accept_call", "decline_call", "prefer_typing", "abuse", "prompt_injection", "other_language", "noise_or_fragment", "affirm", "deny"] as const;
export type Intent = (typeof INTENTS)[number];

export type Channel = "text" | "voice";
export type SlotStatus = "empty" | "candidate" | "filled" | "skipped";
export type NodeKind = "say" | "collect" | "choice" | "terminal";

export const ASK_ORDER: { readonly [C in Channel]: readonly SlotName[] } = {
  text: ["agent_name", "user_name", "need", "gmail"] as const,
  voice: ["user_name", "need", "gmail"] as const,
};

export const SLOT_DESCRIPTIONS: { readonly [S in SlotName]: string } = {
  agent_name: "What the user wants to call their assistant.",
  user_name: "The user's own name (what the assistant should call them).",
  need: "One concrete thing the user wants help with.",
  gmail: "A connected, verified Gmail address.",
};

export const SLOT_WHY: { readonly [S in SlotName]: string } = {
  agent_name: "It's how your assistant will introduce itself to you and sign off emails.",
  user_name: "So your assistant knows who it's working for.",
  need: "Knowing what you need lets your assistant get useful on day one.",
  gmail: "Your assistant works out of your inbox; connecting Gmail lets it read, sort, draft and send for you (always with your OK).",
};

export const NODE_KINDS: { readonly [N in NodeId]: NodeKind } = {
  greet: "say",
  agent_name: "collect",
  call_offer: "choice",
  user_name: "collect",
  need: "collect",
  gmail: "collect",
  value_demo: "say",
  graduated: "terminal",
};

export const TERMINAL_NODE: NodeId = "graduated";
