#!/usr/bin/env node
// Emits apps/web/lib/flow-types.ts from packages/flow/flow.yaml (types + labels only;
// the browser never decides transitions). Zero npm deps: YAML is parsed by the same
// Python + pyyaml the flow tier already needs (PERSONA_PYTHON selects the interpreter).
//   node scripts/flow-types.mjs [--out path] [--check]
import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PY = process.env.PERSONA_PYTHON || "python3";
const args = process.argv.slice(2);
const out = args.includes("--out") ? args[args.indexOf("--out") + 1] : join(ROOT, "apps/web/lib/flow-types.ts");
const SPEC = join(ROOT, "packages/flow/flow.yaml");

const r = spawnSync(PY, ["-c", "import json,sys,yaml; print(json.dumps(yaml.safe_load(open(sys.argv[1]))))", SPEC], {
  encoding: "utf8",
});
if (r.status !== 0) {
  process.stderr.write(r.stderr || "failed to parse flow.yaml\n");
  process.exit(1);
}
const spec = JSON.parse(r.stdout);

const lit = (v) => JSON.stringify(v);
const tuple = (xs) => `[${xs.map(lit).join(", ")}] as const`;
const record = (entries) => `{\n${entries.map(([k, v]) => `  ${k}: ${v},`).join("\n")}\n}`;
const slots = Object.keys(spec.slots);
const nodes = Object.keys(spec.nodes);

const ts = `// GENERATED by \`npm run flow:types\` from packages/flow/flow.yaml — do not edit.
// Types and labels only: transitions are decided by the Python brain, never the browser.

export const FLOW_ID = ${lit(spec.id)};
export const FLOW_VERSION = ${spec.version};

export const SLOT_NAMES = ${tuple(slots)};
export type SlotName = (typeof SLOT_NAMES)[number];

export const NODE_IDS = ${tuple(nodes)};
export type NodeId = (typeof NODE_IDS)[number];

export const INTENTS = ${tuple(spec.intents)};
export type Intent = (typeof INTENTS)[number];

export type Channel = "text" | "voice";
export type SlotStatus = "empty" | "candidate" | "filled" | "skipped";
export type NodeKind = "say" | "collect" | "choice" | "terminal";

export const ASK_ORDER: { readonly [C in Channel]: readonly SlotName[] } = ${record(
  ["text", "voice"].map((c) => [c, tuple(spec.ask_order[c])]),
)};

export const SLOT_DESCRIPTIONS: { readonly [S in SlotName]: string } = ${record(
  slots.map((s) => [s, lit(spec.slots[s].description)]),
)};

export const SLOT_WHY: { readonly [S in SlotName]: string } = ${record(slots.map((s) => [s, lit(spec.slots[s].why)]))};

export const NODE_KINDS: { readonly [N in NodeId]: NodeKind } = ${record(nodes.map((n) => [n, lit(spec.nodes[n].kind)]))};

export const TERMINAL_NODE: NodeId = "graduated";
`;

if (args.includes("--check")) {
  const current = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (current !== ts) {
    console.error(`${out} is stale; run npm run flow:types`);
    process.exit(1);
  }
  console.log(`${out} up to date`);
} else {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, ts);
  console.log(`wrote ${out}`);
}
