#!/usr/bin/env bash
# Full local stack (prod-shaped, no cloud): scratch Postgres -> db-migrate.sh -> agent
# (`python -m agent.main`) -> `next build && next start`. Everything lives under the gitignored
# .persona-local/ (generated secrets, Postgres cluster, pids, logs). Values are never printed.
#
#   scripts/local-stack.sh up [--skip-build]   # start (idempotent: no-op if already up)
#   scripts/local-stack.sh status              # pids + /health + web
#   scripts/local-stack.sh env                 # `export` lines for the live Playwright specs
#   scripts/local-stack.sh smoke               # scripts/deploy/smoke.sh against the local stack
#   scripts/local-stack.sh down [--keep-db|--purge]  # stop; drop the scratch cluster (--purge: all state)
#
# Ports (override via env): LOCAL_AGENT_PORT=8200 LOCAL_WEB_PORT=3200 LOCAL_PG_PORT=55432,
# db LOCAL_DB=persona_local. Python: PERSONA_PYTHON (default python3, needs services/agent deps).
#
# Vendor keys: by default the agent runs OFFLINE (PERSONA_VOICE_FAKE_VENDORS=1, FakeLlm, no TURN,
# no Google) and vendor keys in your shell are ignored. To run with real keys, put KEY=VALUE lines
# in .persona-local/keys.env (chmod 600, gitignored; any ENV.md name, e.g. ANTHROPIC_API_KEY,
# DEEPGRAM_API_KEY, CARTESIA_API_KEY, GOOGLE_OAUTH_CLIENT_ID/SECRET). It is sourced by the agent and
# web processes only; fake vendors are turned off when it provides DEEPGRAM_API_KEY.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PY="${PERSONA_PYTHON:-python3}"
AGENT_PORT="${LOCAL_AGENT_PORT:-8200}"
WEB_PORT="${LOCAL_WEB_PORT:-3200}"
PG_PORT="${LOCAL_PG_PORT:-55432}"
DB="${LOCAL_DB:-persona_local}"
STATE="$ROOT/.persona-local"
PGDATA_DIR="$STATE/pg"
LOGS="$STATE/logs"
SECRETS="$STATE/local.env"   # generated: DB URL, internal secret, token key
KEYS="$STATE/keys.env"       # optional, user-provided vendor keys
AGENT_URL="http://127.0.0.1:$AGENT_PORT"
WEB_URL="http://localhost:$WEB_PORT"
DSN="postgresql://postgres@127.0.0.1:$PG_PORT/$DB"

# Vendor/cloud vars stripped from the inherited shell env (keys.env may set them back).
STRIP="ANTHROPIC_API_KEY DEEPGRAM_API_KEY CARTESIA_API_KEY CLOUDFLARE_TURN_KEY_ID
CLOUDFLARE_TURN_API_TOKEN PERSONA_TURN_URLS PERSONA_TURN_USERNAME PERSONA_TURN_CREDENTIAL
GOOGLE_OAUTH_CLIENT_ID GOOGLE_OAUTH_CLIENT_SECRET GOOGLE_OAUTH_REDIRECT_URL LANGFUSE_PUBLIC_KEY
LANGFUSE_SECRET_KEY PERSONA_TRACING PERSONA_VOICE_FAKE_VENDORS PERSONA_VOICE_STUB_LLM
PERSONA_DATABASE_URL PERSONA_INTERNAL_SECRET PERSONA_TOKEN_ENCRYPT_KEY PERSONA_AGENT_BASE_URL"

say() { echo "local-stack: $*"; }
die() { echo "local-stack: $*" >&2; exit 1; }

usage() { sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; exit 2; }

pid_of() { [ -f "$STATE/$1.pid" ] && cat "$STATE/$1.pid" || true; }
alive() { local p; p="$(pid_of "$1")"; [ -n "$p" ] && kill -0 "$p" 2>/dev/null; }
pg_up() { [ -d "$PGDATA_DIR" ] && pg_ctl -D "$PGDATA_DIR" status >/dev/null 2>&1; }
port_busy() { lsof -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1; }
http_code() { curl -s -o /dev/null -w '%{http_code}' --max-time 5 "$1" 2>/dev/null || true; }

wait_http() { # url seconds pid-name
  local i
  for i in $(seq 1 "$2"); do
    [ "$(http_code "$1")" = 200 ] && return 0
    alive "$3" || { echo "  $3 exited — tail of $LOGS/$3.log:" >&2; tail -20 "$LOGS/$3.log" >&2; return 1; }
    sleep 1
  done
  echo "  timeout after ${2}s waiting for $1 (log: $LOGS/$3.log)" >&2; return 1
}

wait_pidfile() { local i; for i in 1 2 3 4 5 6 7 8 9 10; do [ -s "$STATE/$1.pid" ] && return 0; sleep 0.2; done; die "$1 did not start"; }

need() { command -v "$1" >/dev/null 2>&1 || die "missing $1 ($2)"; }

gen_secrets() {  # once; reused across up/down so sessions/cookies survive a restart
  [ -f "$SECRETS" ] && return 0
  (umask 077
   {
     echo "# generated by scripts/local-stack.sh — local only, never commit"
     echo "PERSONA_DATABASE_URL=$DSN"
     echo "PERSONA_AGENT_BASE_URL=$AGENT_URL"
     echo "PERSONA_INTERNAL_SECRET=$(openssl rand -hex 32)"
     echo "PERSONA_TOKEN_ENCRYPT_KEY=$("$PY" -c 'import base64,os;print(base64.urlsafe_b64encode(os.urandom(32)).decode())')"
   } >"$SECRETS")
  say "generated $SECRETS (names: PERSONA_DATABASE_URL PERSONA_AGENT_BASE_URL PERSONA_INTERNAL_SECRET PERSONA_TOKEN_ENCRYPT_KEY)"
}

# Runs "$@" in a subshell with the local env: shell vendor vars stripped, secrets + keys sourced.
with_env() {
  (
    for v in $STRIP; do unset "$v"; done
    set -a
    . "$SECRETS"
    [ -f "$KEYS" ] && . "$KEYS"
    set +a
    # these always point at the local stack, whatever keys.env says
    PERSONA_DATABASE_URL="$DSN"; PERSONA_AGENT_BASE_URL="$AGENT_URL"
    if [ -z "${DEEPGRAM_API_KEY:-}" ]; then export PERSONA_VOICE_FAKE_VENDORS=1; fi
    "$@"
  )
}

start_pg() {
  need initdb "brew install postgresql@17"; need pg_ctl "brew install postgresql@17"
  if [ ! -d "$PGDATA_DIR" ]; then
    say "initdb scratch cluster ($PGDATA_DIR)"
    initdb -D "$PGDATA_DIR" -A trust -U postgres --no-sync >"$LOGS/initdb.log" 2>&1 \
      || die "initdb failed (log: $LOGS/initdb.log)"
  fi
  if ! pg_up; then
    port_busy "$PG_PORT" && die "port $PG_PORT is busy (set LOCAL_PG_PORT)"
    say "postgres :$PG_PORT"
    # unix socket in /tmp: $STATE may exceed the 103-byte socket path limit
    pg_ctl -D "$PGDATA_DIR" -w -l "$LOGS/postgres.log" \
      -o "-p $PG_PORT -k /tmp -c listen_addresses=127.0.0.1" start >/dev/null \
      || die "postgres failed to start (log: $LOGS/postgres.log)"
  fi
  if ! psql -h 127.0.0.1 -p "$PG_PORT" -U postgres -XAtqc "select 1 from pg_database where datname='$DB'" postgres | grep -q 1; then
    createdb -h 127.0.0.1 -p "$PG_PORT" -U postgres "$DB"
    say "created db $DB"
  fi
  bash "$ROOT/scripts/db-migrate.sh" "$DSN" | sed 's/^/  /'
}

start_agent() {
  if alive agent; then say "agent already running (pid $(pid_of agent))"; return 0; fi
  port_busy "$AGENT_PORT" && die "port $AGENT_PORT is busy (set LOCAL_AGENT_PORT)"
  rm -f "$STATE/agent.pid"
  say "agent :$AGENT_PORT (python -m agent.main)"
  # the inner shell records its own pid, then execs: the pid file names the server itself
  with_env bash -c 'echo $$ >"$4"; cd "$1/services/agent" && exec nohup "$2" -m agent.main --host 127.0.0.1 --port "$3"' \
    _ "$ROOT" "$PY" "$AGENT_PORT" "$STATE/agent.pid" >"$LOGS/agent.log" 2>&1 &
  wait_pidfile agent
  wait_http "$AGENT_URL/health" 90 agent
}

start_web() {
  if alive web; then say "web already running (pid $(pid_of web))"; return 0; fi
  port_busy "$WEB_PORT" && die "port $WEB_PORT is busy (set LOCAL_WEB_PORT)"
  rm -f "$STATE/web.pid"
  local next="$ROOT/node_modules/.bin/next"
  [ -x "$next" ] || die "next not installed — run: npm ci"
  if [ "$SKIP_BUILD" = 1 ] && [ -f "$ROOT/apps/web/.next/BUILD_ID" ]; then
    say "reusing apps/web/.next (--skip-build)"
  else
    say "next build (log: $LOGS/next-build.log)"
    (cd "$ROOT/apps/web" && npm run build) >"$LOGS/next-build.log" 2>&1 \
      || { tail -30 "$LOGS/next-build.log" >&2; die "next build failed"; }
  fi
  say "web :$WEB_PORT (next start)"
  with_env bash -c 'echo $$ >"$4"; cd "$1/apps/web" && exec nohup "$2" start -p "$3"' \
    _ "$ROOT" "$next" "$WEB_PORT" "$STATE/web.pid" >"$LOGS/web.log" 2>&1 &
  wait_pidfile web
  wait_http "$WEB_URL/" 90 web
}

write_e2e_env() {  # non-secret; `set -a; . .persona-local/e2e.env; set +a`
  { echo "PERSONA_E2E_AGENT_URL=$AGENT_URL"; echo "PERSONA_E2E_REAL_AGENT_URL=$AGENT_URL"
    echo "PERSONA_WEB_URL=$WEB_URL"; } >"$STATE/e2e.env"
}

print_env() {
  echo "export PERSONA_E2E_AGENT_URL=$AGENT_URL"
  echo "export PERSONA_E2E_REAL_AGENT_URL=$AGENT_URL"
  echo "export PERSONA_WEB_URL=$WEB_URL"
}

cmd_up() {
  need curl ""; need lsof ""; need openssl ""; need psql "brew install libpq"
  mkdir -p "$STATE" "$LOGS"; chmod 700 "$STATE"
  gen_secrets
  start_pg
  start_agent
  start_web
  write_e2e_env
  echo
  say "UP — web $WEB_URL  agent $AGENT_URL  db $DB@127.0.0.1:$PG_PORT"
  if [ -f "$KEYS" ]; then say "keys: .persona-local/keys.env ($(sed -n 's/^\(export \)\{0,1\}\([A-Z_][A-Z0-9_]*\)=.*/\2/p' "$KEYS" | tr '\n' ' '))"
  else say "keys: none — offline mode (fake voice vendors, FakeLlm, no Google OAuth)"; fi
  echo "  agent /health: $(curl -fsS --max-time 5 "$AGENT_URL/health" 2>/dev/null | head -c 300)"
  echo "  web /: HTTP $(http_code "$WEB_URL/")"
  echo "  Playwright against this stack (real-agent specs; specs that seed() need the stub agent):"
  print_env | sed 's/^/    /'
  echo "    (cd apps/web && npx playwright test e2e/real-agent-call.spec.ts e2e/ec-08-refresh-resume.spec.ts --project=desktop)"
}

stop_pid() {
  local name="$1" p i
  p="$(pid_of "$name")"
  if [ -n "$p" ] && kill -0 "$p" 2>/dev/null; then
    pkill -TERM -P "$p" 2>/dev/null || true   # children first (e.g. next's worker)
    kill "$p" 2>/dev/null || true
    for i in 1 2 3 4 5 6 7 8 9 10; do kill -0 "$p" 2>/dev/null || break; sleep 0.5; done
    kill -0 "$p" 2>/dev/null && kill -9 "$p" 2>/dev/null || true
    say "stopped $name (pid $p)"
  fi
  rm -f "$STATE/$name.pid"
}

cmd_down() {
  local mode="${1:-}"
  case "$mode" in ""|--keep-db|--purge) ;; *) usage ;; esac
  [ -d "$STATE" ] || { say "nothing to stop"; return 0; }
  stop_pid web
  stop_pid agent
  if pg_up; then pg_ctl -D "$PGDATA_DIR" -m fast -w stop >/dev/null 2>&1 || true; say "stopped postgres"; fi
  if [ "$mode" = --keep-db ]; then say "kept $PGDATA_DIR"
  else rm -rf "$PGDATA_DIR"; say "removed scratch cluster"; fi
  rm -f "$STATE/e2e.env"
  if [ "$mode" = --purge ]; then rm -rf "$STATE"; say "purged .persona-local/"; fi
  for port in "$AGENT_PORT" "$WEB_PORT" "$PG_PORT"; do
    port_busy "$port" && echo "local-stack: WARNING port $port still has a listener (not ours?)" >&2
  done
  say "DOWN"
}

cmd_status() {
  local rc=0 name
  for name in agent web; do
    if alive "$name"; then echo "  $name  pid $(pid_of "$name")"; else echo "  $name  not running"; rc=1; fi
  done
  if pg_up; then echo "  postgres  :$PG_PORT ($DB)"; else echo "  postgres  not running"; rc=1; fi
  echo "  agent /health: HTTP $(http_code "$AGENT_URL/health")"
  echo "  web /: HTTP $(http_code "$WEB_URL/")"
  [ "$(http_code "$AGENT_URL/health")" = 200 ] && [ "$(http_code "$WEB_URL/")" = 200 ] || rc=1
  return $rc
}

cmd_smoke() {
  # Offline stack: no Google client and STUN-only ICE are expected, so those checks don't fail it.
  local skip_oauth=1
  [ -f "$KEYS" ] && grep -q '^\(export \)\{0,1\}GOOGLE_OAUTH_CLIENT_ID=.' "$KEYS" && skip_oauth=0
  SMOKE_SKIP_OAUTH="$skip_oauth" SMOKE_REQUIRE_TURN=0 \
    bash "$ROOT/scripts/deploy/smoke.sh" "$WEB_URL" "$AGENT_URL"
}

SKIP_BUILD=0
case "${1:-}" in
  up) shift; [ "${1:-}" = --skip-build ] && SKIP_BUILD=1; cmd_up ;;
  down) shift; cmd_down "${1:-}" ;;
  status) cmd_status ;;
  env) print_env ;;
  smoke) cmd_smoke ;;
  *) usage ;;
esac
